### ISSUE TITLE
Parser crashes on strings that contain U+201D (RIGHT DOUBLE QUOTATION MARK)

### ISSUE THREAD

**Issue by hollasch** [yaml/pyyaml#147]
I'm getting a crash in Python 3 on Windows when parsing YAML files that contain strings with right quotation marks. This is in a UTF-8 encoded YAML file. I've tested both with and without BOM.

### Stack Trace
```
Traceback (most recent call last):
  File "A:\srh\TEALS\repo\apcsa\apcsa-instructor\qbank\testgen.py", line 111, in <module>
    sys.exit (main())
  File "A:\srh\TEALS\repo\apcsa\apcsa-instructor\qbank\testgen.py", line 14, in main
    spec = read_spec (sys.argv[1])
  File "A:\srh\TEALS\repo\apcsa\apcsa-instructor\qbank\testgen.py", line 46, in read_spec
    return yaml.load(stream)
  File "C:\Python36\lib\site-packages\yaml\__init__.py", line 70, in load
    loader = Loader(stream)
  File "C:\Python36\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Python36\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Python36\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Python36\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 315: character maps to <undefined>
```

**Comment by ingydotnet** [comment]
@hollasch I found this url: http://www.pitt.edu/~naraehan/python3/mbb12.html

Look at the "Learn More" section. If you are reading the yaml text from a file, then it looks like you might need to specify the encoding: `open(yaml_file, encoding="utf-8")`.

I'm going to close this for now, but if this is not the right fix, then go ahead and reopen it and also post some replication code and the yaml you are trying to load.

**Comment by hollasch** [comment]
The `encoding` argument eliminates the exception. When printed out, it looks like it emits the characters (left & right double quotation marks) in the Windows 1252 code page (hex 0x93, 0x94). But as far as PyYAML is concerned, it looks like your suggestion is good, and there's no bug here.
