### ISSUE TITLE
Should pyyaml really try to match hash key aggressively in list items ?

### ISSUE THREAD

**Issue by jpic** [yaml/pyyaml#230]
Given a doc like this:

```
---
name: dumpdata
script:
- django-admin mrsstat --refresh
- django-admin
    dumpdata
    --indent=4 $(grep model src/mrs/tests/data.json | sort -u | sed 's/.*model": "\([^"]*\)",*/\1/')
    > src/mrs/tests/data.json
```

PyYaml will fail as such:

```
Traceback (most recent call last):
  File "/home/jpic/.local/bin/autoplay", line 11, in <module>
    load_entry_point('autoplay', 'console_scripts', 'autoplay')()
  File "/home/jpic/src/autoplay/autoplay/cli.py", line 41, in main
    schema = Schema.cli()
  File "/home/jpic/src/autoplay/autoplay/schema.py", line 38, in cli
    self.parse(path)
  File "/home/jpic/src/autoplay/autoplay/schema.py", line 12, in parse
    docs = [yaml.load(i) for i in f.read().split('---')]
  File "/home/jpic/src/autoplay/autoplay/schema.py", line 12, in <listcomp>
    docs = [yaml.load(i) for i in f.read().split('---')]
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/parser.py", line 403, in parse_indentless_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/home/jpic/.local/lib/python3.7/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 7, column 80:
     ... json | sort -u | sed 's/.*model": "\([^"]*\)",*/\1/')
                                         ^
```

I suppose it's trying to match a multiline hash key in that list item, at the same time that means that you may not have list item string that contains `:`

What do you think ?

**Comment by ingydotnet** [comment]
Try using a folded scalar like this:

```---
name: dumpdata
script:
- django-admin mrsstat --refresh
- >
  django-admin
    dumpdata
    --indent=4 $(grep model src/mrs/tests/data.json | sort -u | sed 's/.*model": "\([^"]*\)",*/\1/')
    > src/mrs/tests/data.json```
