### ISSUE TITLE
Unable to dump with the same format loaded

### ISSUE THREAD

**Issue by Peque** [yaml/pyyaml#283]
Let us load a simple string that contains a `!!timestamp`:

```python
>>> x = yaml.safe_load('begin: !!timestamp 2015-1-1')
>>> x
{'begin': datetime.date(2015, 1, 1)}
```

Now, `safe_dump` would convert the `datetime` to `str`:

```python
>>> yaml.safe_dump(x)
'begin: 2015-01-01\n'
```

How can I change that? I have also tried:

```python
>>> yaml.dump(x, Dumper=yaml.dumper.SafeRepresenter)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peque/.conda/envs/python36/lib/python3.6/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/peque/.conda/envs/python36/lib/python3.6/site-packages/yaml/__init__.py", line 274, in dump_all
    explicit_start=explicit_start, explicit_end=explicit_end, sort_keys=sort_keys)
TypeError: __init__() got multiple values for argument 'default_style'
```

**Comment by perlpunk** [comment]
> Now, safe_dump would convert the datetime to str:

Why do you think that?

```
Python 2.7.14+ (default, Dec  5 2017, 15:17:02)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> x = yaml.safe_load('begin: !!timestamp 2015-1-1')
>>> x
{'begin': datetime.date(2015, 1, 1)}
>>> y = yaml.safe_dump(x)
>>> y
'begin: 2015-01-01\n'
>>> x = yaml.safe_load(y)
>>> x
{'begin': datetime.date(2015, 1, 1)}
```
`2015-01-01` is recognized as a timestamp again automatically. the `!!timestamp` is optional.

**Comment by perlpunk** [comment]
Closing; please reopen if this behaves differently for you
