### ISSUE TITLE
dump a object with __slots__ then load it will throw TypeError

### ISSUE THREAD

**Issue by Hanaasagi** [yaml/pyyaml#284]
## Long story short

Both

- PyYAML-3.12
- PyYAML-5.1

Following code will crash.

```Python
import yaml


class A:
    __slots__ = ('c', )

    def __init__(self):
        self.c = 3


data = yaml.dump({'a': A()})
d = yaml.load(data)
```

Output

```
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    d = yaml.load(data)
  File "/root/py36/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 617, in construct_python_object_new
    return self.construct_python_object_apply(suffix, node, newobj=True)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 608, in construct_python_object_apply
    self.set_python_instance_state(instance, state)
  File "/root/py36/lib/python3.7/site-packages/yaml/constructor.py", line 570, in set_python_instance_state
    setattr(object, key, value)
TypeError: can't set attributes of built-in/extension type 'object'
```

I have opened a pull request #258, but no one has time to see. And I really want this fix to appear in next version.

**Comment by perlpunk** [comment]
Fixed in 5.3: https://pypi.org/project/PyYAML/5.3/
