### ISSUE TITLE
dump raises "Unicode argument expected, got 'str'"

### ISSUE THREAD

**Issue by fchauvel** [yaml/pyyaml#289]
I'm trying to get [a project](https://github.com/STAMP-project/camp) to run on both Python 2.7 to Python 3.5, but I'm facing an issue when I dump a dictionary into a StringIO object. Here is an example, I run on Debian 9 / Python 2.7.13 / PyYAML 5.1:

```python
from __future__ import unicode_literals
from io import StringIO
from yaml import safe_dump

output = StringIO()
data = { "reports": "bonjour" }
safe_dump(data, output, allow_unicode=True)

print(output.getvalue())
```

When I run it, I got an error "Unicode argument expected, got 'str'" as you can see below:
```console
(.py2.7) fchauvel@debian:~/Documents/camp$ python bidon.py                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                 
  File "bidon.py", line 11, in <module>                                                                                                                                                                            
    safe_dump(data, output, allow_unicode=True)                                                                                                                                                                    
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/__init__.py", line 309, in safe_dump                                                                                           
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)                                                                                                                                                     
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/__init__.py", line 281, in dump_all                                                                                            
    dumper.represent(data)                                                                                                                                                                                         
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/representer.py", line 30, in represent                                                                                         
    self.serialize(node)                                                                                                                                                                                           
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/serializer.py", line 54, in serialize                                                                                          
    self.serialize_node(node, None, None)                                                                                                                                                                          
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/serializer.py", line 109, in serialize_node                                                                                    
    self.emit(MappingEndEvent())                                                                                                                                                                                   
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/emitter.py", line 119, in emit                                                                                                 
    self.state()                                                                                                                                                                                                   
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/emitter.py", line 398, in expect_first_block_mapping_key                                                                       
    return self.expect_block_mapping_key(first=True)                                                                                                                                                               
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/emitter.py", line 408, in expect_block_mapping_key                                                                             
    self.expect_node(mapping=True, simple_key=True)                                                                                                                                                                
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/emitter.py", line 249, in expect_node                                                                                          
    self.expect_scalar()                                                                                                                                                                                           
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/emitter.py", line 273, in expect_scalar                                                                                        
    self.process_scalar()                                                                                                                                                                                          
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/emitter.py", line 538, in process_scalar                                                                                       
    self.write_plain(self.analysis.scalar, split)                                                                                                                                                                  
  File "/home/fchauvel/Documents/camp/.py2.7/local/lib/python2.7/site-packages/yaml/emitter.py", line 1139, in write_plain                                                                                         
    self.stream.write(data)                                                                                                                                                                                        
TypeError: unicode argument expected, got 'str'  
```
The code works under Python 3.5. Any work around for the Python2.7 that would also work for Python 3.5?

Thanks in advance.

**Comment by Hanaasagi** [comment]
Hi @fchauvel 
Have a look of https://python-future.org/compatible_idioms.html#stringio

```Python
from __future__ import unicode_literals

from yaml import safe_dump

try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO

output = StringIO()
data = {"reports": "bonjour"}
safe_dump(data, output, allow_unicode=True)
output.seek(0)
assert output.read() == 'reports: bonjour\n'
```

or just use [`six.StringIO`](https://pythonhosted.org/six/#six.StringIO).

I tested it in Python 2.7 and Python 3.7.
