### ISSUE TITLE
AssertionError: 'expected an exception'

### ISSUE THREAD

**Issue by kyrios123** [yaml/pyyaml#298]
I got the following errors during the tests
- libyaml:  0.2.2
- pyyaml: 3.13
- python: 2.7.16 and 3.6.8
- x86_64 GNU/Linux 5.0.7
```
===========================================================================
test_loader_error_ext(tests/data/colon-in-flow-context.loader-error): FAILURE
Traceback (most recent call last):
  File "tests/lib/test_appliance.py", line 65, in execute
    function(verbose=verbose, *filenames)
  File "tests/lib/test_yaml_ext.py", line 240, in wrapper
    function(*args, **kwds)
  File "tests/lib/test_errors.py", line 11, in test_loader_error
    raise AssertionError("expected an exception")
AssertionError: see below
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'expected an exception'
---------------------------------------------------------------------------
tests/data/colon-in-flow-context.loader-error:
{ foo:bar }
===========================================================================
test_loader_error_string_ext(tests/data/colon-in-flow-context.loader-error): FAILURE
Traceback (most recent call last):
  File "tests/lib/test_appliance.py", line 65, in execute
    function(verbose=verbose, *filenames)
  File "tests/lib/test_yaml_ext.py", line 240, in wrapper
    function(*args, **kwds)
  File "tests/lib/test_errors.py", line 22, in test_loader_error_string
    raise AssertionError("expected an exception")
AssertionError: see below
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'expected an exception'
---------------------------------------------------------------------------
tests/data/colon-in-flow-context.loader-error:
{ foo:bar }
===========================================================================
TESTS: 2573
FAILURES: 2
```

**Comment by FRidh** [comment]
With 5.1:

```
===========================================================================
test_emitter_styles_ext(tests/data/spec-07-09.data, tests/data/spec-07-09.canonical): FAILURE
Traceback (most recent call last):
  File "tests/lib3/test_appliance.py", line 59, in execute
    function(verbose=verbose, *filenames)
  File "tests/lib3/test_yaml_ext.py", line 240, in wrapper
    function(*args, **kwds)
  File "tests/lib3/test_emitter.py", line 62, in test_emitter_styles
    _compare_events(events, new_events)
  File "tests/lib3/test_emitter.py", line 15, in _compare_events
    assert event1.value == event2.value, (event1, event2)
AssertionError: see below
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(ScalarEvent(anchor=None, tag='tag:yaml.org,2002:str', implicit=(False, False), value='foo'),
 ScalarEvent(anchor=None, tag='tag:yaml.org,2002:str', implicit=(False, False), value='foo %YAML 1.1'))
---------------------------------------------------------------------------
tests/data/spec-07-09.data:
---
foo
...
# Repeated end marker.
...
---
bar
# No end marker.
---
baz
...
---------------------------------------------------------------------------
tests/data/spec-07-09.canonical:
%YAML 1.1
---
!!str "foo"
%YAML 1.1
---
!!str "bar"
%YAML 1.1
---
!!str "baz"
===========================================================================
test_emitter_styles_ext(tests/data/spec-07-10.data, tests/data/spec-07-10.canonical): FAILURE
Traceback (most recent call last):
  File "tests/lib3/test_appliance.py", line 59, in execute
    function(verbose=verbose, *filenames)
  File "tests/lib3/test_yaml_ext.py", line 240, in wrapper
    function(*args, **kwds)
  File "tests/lib3/test_emitter.py", line 62, in test_emitter_styles
    _compare_events(events, new_events)
  File "tests/lib3/test_emitter.py", line 15, in _compare_events
    assert event1.value == event2.value, (event1, event2)
AssertionError: see below
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(ScalarEvent(anchor=None, tag='tag:yaml.org,2002:str', implicit=(False, False), value='Root flow scalar'),
 ScalarEvent(anchor=None, tag='tag:yaml.org,2002:str', implicit=(False, False), value='Root flow scalar %YAML 1.1'))
---------------------------------------------------------------------------
tests/data/spec-07-10.data:
"Root flow
 scalar"
--- !!str >
 Root block
 scalar
---
# Root collection:
foo : bar
... # Is optional.
---
# Explicit document may be empty.
---------------------------------------------------------------------------
tests/data/spec-07-10.canonical:
%YAML 1.1
---
!!str "Root flow scalar"
%YAML 1.1
---
!!str "Root block scalar\n"
%YAML 1.1
---
!!map {
  ? !!str "foo"
  : !!str "bar"
}
---
#!!str ""
!!null ""
===========================================================================
test_emitter_styles_ext(tests/data/spec-07-13.data, tests/data/spec-07-13.canonical): FAILURE
Traceback (most recent call last):
  File "tests/lib3/test_appliance.py", line 59, in execute
    function(verbose=verbose, *filenames)
  File "tests/lib3/test_yaml_ext.py", line 240, in wrapper
    function(*args, **kwds)
  File "tests/lib3/test_emitter.py", line 62, in test_emitter_styles
    _compare_events(events, new_events)
  File "tests/lib3/test_emitter.py", line 15, in _compare_events
    assert event1.value == event2.value, (event1, event2)
AssertionError: see below
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(ScalarEvent(anchor=None, tag='!foo', implicit=(False, False), value='No directives'),
 ScalarEvent(anchor=None, tag='!foo', implicit=(False, False), value='No directives %TAG ! %21foo'))
---------------------------------------------------------------------------
tests/data/spec-07-13.data:
! "First document"
---
!foo "No directives"
%TAG ! !foo
---
!bar "With directives"
%YAML 1.1
---
!baz "Reset settings"
---------------------------------------------------------------------------
tests/data/spec-07-13.canonical:
%YAML 1.1
---
!!str "First document"
---
!<!foo> "No directives"
---
!<!foobar> "With directives"
---
!<!baz> "Reset settings"
===========================================================================
test_emitter_styles_ext(tests/data/spec-08-08.data, tests/data/spec-08-08.canonical): FAILURE
Traceback (most recent call last):
  File "tests/lib3/test_appliance.py", line 59, in execute
    function(verbose=verbose, *filenames)
  File "tests/lib3/test_yaml_ext.py", line 240, in wrapper
    function(*args, **kwds)
  File "tests/lib3/test_emitter.py", line 62, in test_emitter_styles
    _compare_events(events, new_events)
  File "tests/lib3/test_emitter.py", line 15, in _compare_events
    assert event1.value == event2.value, (event1, event2)
AssertionError: see below
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(ScalarEvent(anchor=None, tag='tag:yaml.org,2002:str', implicit=(False, False), value='foo bar'),
 ScalarEvent(anchor=None, tag='tag:yaml.org,2002:str', implicit=(False, False), value='foo bar %YAML 1.1'))
---------------------------------------------------------------------------
tests/data/spec-08-08.data:
---
foo:
 "bar
 baz"
---
"foo
 bar"
---
foo
 bar
--- |
 foo
...
---------------------------------------------------------------------------
tests/data/spec-08-08.canonical:
%YAML 1.1
---
!!map {
  ? !!str "foo"
  : !!str "bar baz"
}
%YAML 1.1
---
!!str "foo bar"
%YAML 1.1
---
!!str "foo bar"
%YAML 1.1
---
!!str "foo\n"
===========================================================================
TESTS: 2602
FAILURES: 4
error: Tests failed
builder for '/nix/store/dm5kjkylawq31ag4v289s2p1danf5n5m-python3.7-PyYAML-5.1.drv' failed with exit code 1
```

**Comment by perlpunk** [comment]
Could you check if it is related to #320 and an outdated libyaml tarball?

**Comment by FRidh** [comment]
No, it is unrelated. This really uses 0.2.2, from GitHub.

**Comment by perlpunk** [comment]
Oh right, sorry for not looking closer.
So, the test file `tests/data/colon-in-flow-context.loader-error` was removed in commit c5b135fe39d41cffbdc006f28ccb2032df6005e0 because `{ foo:bar }` is now recognized as valid YAML (both in PyYAML >= 5 and the newest libyaml).

So using an older PyYAML with a newer libyaml can lead to such test failures.

**Comment by perlpunk** [comment]
Closing
