### ISSUE TITLE
Valid .yaml generates error "yaml.scanner.ScannerError: mapping values are not allowed here"

### ISSUE THREAD

**Issue by stefanodallapalma** [yaml/pyyaml#318]
Given the following yaml file:

```yaml
- include: ../common_playbooks/validate_environment.yml
  gather_facts: false
```

running the following python script 

```python

import yaml

s = '- include: ../common_playbooks/validate_environment.yml\
- gather_facts: false'

yaml.safe_load(s)
```

produces the following output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/user/.local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/user/.local/lib/python3.6/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/home/user/.local/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/user/.local/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/user/.local/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/user/.local/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/user/.local/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/.local/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/user/.local/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/user/.local/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/user/.local/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/user/.local/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/user/.local/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 1, column 70:
     ... te_environment.yml- gather_facts: false
                                                              ^
```

Do you have any idea? By the way, the yaml seems to be valid for [this yaml lint](http://www.yamllint.com).

**Comment by perlpunk** [comment]
You are missing a newline when constructing the string. Just print the string to see.
```
>>> s = '- include: ../common_playbooks/validate_environment.yml\  
... - gather_facts: false'  
>>>  
>>> s 
'- include: ../common_playbooks/validate_environment.yml- gather_facts: false'
>>>

**Comment by stefanodallapalma** [comment]
Yeah, you rigth! Noticed that. 
The problem was that for some reason the newline was not recognize when loading the file containing that code.

Thanks
