### ISSUE TITLE
Parsing error while defining same alias

### ISSUE THREAD

**Issue by whg517** [yaml/pyyaml#334]
```python
# encoding: utf-8

import yaml

doc = """%YAML 1.2
---
- config:
    filename: &filename xxx
  metadata:
    xx:
      file: *filename
- config:
    filename: &filename yyy
  metadata:
    xx:
      file: *filename
"""

yaml.load(doc, yaml.SafeLoader)
```

```
Traceback (most recent call last):
  File "/home/kevin/workspaces/develop/python/data_trans/tran_20190911/__init__.py", line 19, in <module>
    yaml.load(doc, yaml.SafeLoader)
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/kevin/.virtualenvs/data_trans-La80qRSB/lib/python3.6/site-packages/yaml/composer.py", line 77, in compose_node
    "second occurrence", event.start_mark)
yaml.composer.ComposerError: found duplicate anchor 'filename'; first occurrence
  in "<unicode string>", line 4, column 15:
        filename: &filename xxx
                  ^
second occurrence
  in "<unicode string>", line 9, column 15:
        filename: &filename yyy
                  ^

Process finished with exit code 1
```

The [Alias Nodes](https://yaml.org/spec/1.2/spec.html#id2786196) example by yaml spec is multi-anchor capable.

How do I need to use it correctly?

Thank you for your help.

**Comment by perlpunk** [comment]
Duplicate of #100
