### ISSUE TITLE
Trivial crash with IndexError

### ISSUE THREAD

**Issue by Google-Autofuzz** [yaml/pyyaml#357]
```
$ cat test.py 
import yaml
yaml.load('!!float')
```

```
$ python3 test.py 
test.py:3: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml.load('!!float')
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    yaml.load('!!float')
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 47, in construct_document
    data = self.construct_object(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 266, in construct_yaml_float
    if value[0] == '-':
IndexError: string index out of range
$
```

**Comment by Google-Autofuzz** [comment]
```python
$ cat test.py 
import sys
import yaml

with open(sys.argv[1]) as f:
  yaml.load(f.read(), Loader=yaml.CLoader)
```

crash-0d85f459420c2c1ef3cbc010935ab50b5e65c61b's  content:
```yaml
3:
63833:9.:

33:
33333333333.:
333:333333333:3.:

:3:
3333:
333333861:5:5:5:1:0:1:1:0:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:5:1:0:0:1:1:0:0:1:11:0:0:1:0:11:0:2:5:1:5:1:1:0:1:1:0:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:1:0:00:0:1:1:0:1:0:0:1:11:0:0:1:1:0:0:1:0:11:01:1:0:00:0:1:1:5:1:0:0:1:1:0:0:1:11:0:0:1:0:11:0:2:5:1:5:1:1:0:1:1:0:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:1:0:00:0:1:1:5:1:0:0:1:11:0:0:1:1:0:0:1:0:11:0:0:1:11:0:0:1:0:11:0:2:5:1:5:1:1:0:1:1:0:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:1:0:00:0:1:1:5:1:0:0:1:11:0:0:1:0:11:0:0:1:11:0:0:1:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:1:0:00:0:1:1:5:1:0:0:1:11:0:0:1:0:11:0:0:1:11:0:0:1:0:11:0:2:5:1:5:1:0:0:3.:

1:11:0:0:1:0:1:0:0:1:::::11:0:1: 
```

```python
$ python3 ./test.py crash-0d85f459420c2c1ef3cbc010935ab50b5e65c61b 
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    yaml.load(f.read(), Loader=yaml.CLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 131, in construct_mapping
    key = self.construct_object(key_node, deep=deep)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 280, in construct_yaml_float
    value += digit*base
OverflowError: int too large to convert to float
```

**Comment by Google-Autofuzz** [comment]
```python
$ cat test.py 
import sys
import yaml

with open(sys.argv[1]) as f:
  yaml.load(f.read(), Loader=yaml.CLoader
```

crash-b3509a0cfdc3f687cae1558e79b1a62bac39964e's content:

```yaml
!!float  i   
```

```python
$ python3 ./test.py crash-b3509a0cfdc3f687cae1558e79b1a62bac39964e
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    yaml.load(f.read(), Loader=yaml.CLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 47, in construct_document
    data = self.construct_object(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 284, in construct_yaml_float
    return sign*float(value)
ValueError: could not convert string to float: 'i'
$
```

**Comment by Google-Autofuzz** [comment]
```python
$ cat test.py 
import sys
import yaml

with open(sys.argv[1]) as f:
  yaml.load(f.read(), Loader=yaml.CLoader
```

crash-b3509a0cfdc3f687cae1558e79b1a62bac39964e's content:

```yaml
0b_
```

```python
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    yaml.load(f.read(), Loader=yaml.CLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 47, in construct_document
    data = self.construct_object(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 240, in construct_yaml_int
    return sign*int(value[2:], 2)
ValueError: invalid literal for int() with base 2: ''
$
```

**Comment by Google-Autofuzz** [comment]
```python
$ cat test.py 
import sys
import yaml

with open(sys.argv[1]) as f:
  yaml.load(f.read(), Loader=yaml.CLoader
```

crash-90182323d24024add845deaee149b063333097fe's content:

```yaml
- -  - - - -  - - -  -   - - -  - - -  - - - -  - - -  -   - - -  - - - -  - - -  -   - - -  - - -  - - - -  - - -  -   - - -  - - -  - -  - -  - - -  - - -  -   - - -  - - - -  -   - - -  - - -  -  -  - -   - -  -  - -  - - -  - - -  -   - - -  - - -  -  -  - -  - - - - - -  - -  - - -  - - - - - -  -  - -  - - -  -   - - - -  - - -  -   - - -  - - -  - - - -  - - -  -   - - -  - - -  -  -  - -  - - - - - -  - -  -  - -  - - -  - - -  -   - - -  - - -  -  -  - -   - -  -  - -  - - -  - - -  -   - - -  - - - -  -   - - -  - - -  -  -  - -   - -  -  - -  - - -  - - -  -   - - -  - - -  -  -  - -  - - - -  - -  - - - - - -  - -  - -    - - -  - - -  -  -  - -   - -  -  - -  - -  -  -   - - -  - - - -  -   - - -  - - -  -  -  - -   - -  -    - - -  - - -  -   - - -  - - -  -  -  - -  - - - - - -  - -  - -  - - - -  -  /  -  - -  - -  - - - - - -  - - -  - - - -  
```

```python
FuzzError: Traceback (most recent call last):  File "./test.py", line 5, in <module>
    yaml.load(f.read(), Loader=yaml.CLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/usr/lib/python3/dist-packages/epresenter.py3", line 26, in represent
    node = self.represent_data(data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
[…]
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib/python3/dist-packages//yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 91, in represent_sequence
    node_item = self.represent_data(item)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 47, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 197, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 86, in represent_sequence
    node = SequenceNode(tag, value, flow_style=flow_style)
RecursionError: maximum recursion depth exceeded
$
```

**Comment by dota17** [comment]
@nitzmahone
this issue is same as #382 / #434  in a sense.
```
!!float
!!float i
333333861:5:5:5:1:0:1:1:0:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:5:1:0:0:1:1:0:0:1:11:0:0:1:0:11:0:2:5:1:5:1:1:0:1:1:0:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:1:0:00:0:1:1:0:1:0:0:1:11:0:0:1:1:0:0:1:0:11:01:1:0:00:0:1:1:5:1:0:0:1:1:0:0:1:11:0:0:1:0:11:0:2:5:1:5:1:1:0:1:1:0:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:1:0:00:0:1:1:5:1:0:0:1:11:0:0:1:1:0:0:1:0:11:0:0:1:11:0:0:1:0:11:0:2:5:1:5:1:1:0:1:1:0:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:1:0:00:0:1:1:5:1:0:0:1:11:0:0:1:0:11:0:0:1:11:0:0:1:11:0:2:5:1:5:1:0:0:1:11:0:0:1:0:1:0:0:1:1:5:1:1:0:00:0:1:1:5:1:0:0:1:11:0:0:1:0:11:0:0:1:11:0:0:1:0:11:0:2:5:1:5:1:0:0:3.:
```
Could we choose to convert them into string instead of throwing an exception.

**Comment by drawks** [comment]
> Could we choose to convert them into string instead of throwing an exception.

I think the standard says that is exactly what should be done https://yaml.org/spec/1.2/spec.html#id2767381

**Comment by nitzmahone** [comment]
Yes and no- the spec and the various schema/datatype definitions are pretty vague about how implementations should distinguish semantic validity vs well-formedness. IIRC the common datatypes are defined by their various specs only in terms of regexes, not semantic validity or native type represent-ability. 

If we go down this road, IMO it's very important that we preserve the distinction between implicit resolver failures and native representation failures of explicitly tagged data. I have no problem with allowing an untagged scalar to fall back to a string if it can't be represented natively by a matching implicit resolver, but at least by default, an explicitly tagged scalar (ie this case) that can't be represented by the implementation's chosen native datatype should continue to be a failure.

@ingy any thoughts to add?
