### ISSUE TITLE
 Fatal crash due to uncaught exception in datetime for 0000-00-00 

### ISSUE THREAD

**Issue by reyjrar** [yaml/pyyaml#382]
Given the document:

```yaml
---
field: 0000-00-00
```
I would expect that the document would have a field element with type string.

[According to the flow for handling casting to native data structures](https://yaml.org/spec/1.2/spec.html#id2767381) I would expect complete or partial representation of the field element, not a fatal error due to an invalid date.

Yes, that string does match the [!!timestamp regex](https://yaml.org/type/timestamp.html), so it's correct that it try to load it as a native python datetime. However, failing that, it should be represented as a string in the document because '0000-00-00' is, in fact, a valid string.

This also makes me suspicious that other data types aren’t being properly exception handled, but I’m just tripping over this one right now.

**Comment by drawks** [comment]
I can confirm this behavior is still present in the current version released via pypi
```
$ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.__version__
'5.3.1'
>>> yaml.load('---\n  baddate: 0000-00-00')
__main__:1: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/drawks/pyyaml.test/local/lib/python2.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/drawks/pyyaml.test/local/lib/python2.7/site-packages/yaml/constructor.py", line 76, in get_single_data
    return self.construct_document(node)
  File "/home/drawks/pyyaml.test/local/lib/python2.7/site-packages/yaml/constructor.py", line 85, in construct_document
    for dummy in generator:
  File "/home/drawks/pyyaml.test/local/lib/python2.7/site-packages/yaml/constructor.py", line 436, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/drawks/pyyaml.test/local/lib/python2.7/site-packages/yaml/constructor.py", line 245, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/drawks/pyyaml.test/local/lib/python2.7/site-packages/yaml/constructor.py", line 170, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/drawks/pyyaml.test/local/lib/python2.7/site-packages/yaml/constructor.py", line 125, in construct_object
    data = constructor(self, node)
  File "/home/drawks/pyyaml.test/local/lib/python2.7/site-packages/yaml/constructor.py", line 349, in construct_yaml_timestamp
    return datetime.date(year, month, day)
ValueError: year is out of range
```

I'd like to cook a fix for this, can anyone (maybe @ingy or another active project member) comment on how such a behavioral change would be received?

To be clear, it is my understanding that any scalar value may be subject to casting to a native type if it matches one of the regexes outlined in the yaml standard's type descriptions, but if casting to a native type fails the scalar should always fall back to being cast as a string.

**Comment by drawks** [comment]
FWIW some of the crashers in #357 appear to be the same class of error as this
