### ISSUE TITLE
yaml.reader.ReaderError: unacceptable character

### ISSUE THREAD

**Issue by ssbarnea** [yaml/pyyaml#397]
It seems that even the latest 5.3 version would raise an exception when trying to load blocks with ESC (0x1b) code in them. YAML spec is clear that the pipe-blocks must be loaded as-is, without any escaping being needed or possible.

```
>>> f = open('a.yml')
>>> x = yaml.safe_load(f)
>>> Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/ssbarnea/.pyenv/versions/3.7.6/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
return load(stream, SafeLoader)
File "/Users/ssbarnea/.pyenv/versions/3.7.6/lib/python3.7/site-packages/yaml/__init__.py", line 112, in load
loader = Loader(stream)
File "/Users/ssbarnea/.pyenv/versions/3.7.6/lib/python3.7/site-packages/yaml/loader.py", line 34, in __init__
Reader.__init__(self, stream)
File "/Users/ssbarnea/.pyenv/versions/3.7.6/lib/python3.7/site-packages/yaml/reader.py", line 85, in __init__
self.determine_encoding()
File "/Users/ssbarnea/.pyenv/versions/3.7.6/lib/python3.7/site-packages/yaml/reader.py", line 135, in determine_encoding
self.update(1)
File "/Users/ssbarnea/.pyenv/versions/3.7.6/lib/python3.7/site-packages/yaml/reader.py", line 169, in update
self.check_printable(data)
File "/Users/ssbarnea/.pyenv/versions/3.7.6/lib/python3.7/site-packages/yaml/reader.py", line 144, in check_printable
'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x001b: special characters are not allowed
in "a.yml", position 183
```

The file containing the special character can be loaded from https://gist.githubusercontent.com/ssbarnea/c162d9c96efd7d2a52e455892183b649/raw/88a8d4f8ce5ec0410b491dab53593428a859efc9/a.yml

**Comment by perlpunk** [comment]
Control characters can never be literal in YAML, see
https://yaml.org/spec/1.2/spec.html#id2770814
> To ensure readability, YAML streams use only the printable subset of the Unicode character set. The allowed character range explicitly excludes the **C0 control block #x0-#x1F** (except for TAB #x9, LF #xA, and CR #xD which are allowed), DEL #x7F, the C1 control block #x80-#x9F (except for NEL #x85 which is allowed), the surrogate block #xD800-#xDFFF, #xFFFE, and #xFFFF.
