### ISSUE TITLE
CSafeLoader fails to load 

### ISSUE THREAD

**Issue by Dbandfield** [yaml/pyyaml#443]
Hello. The CSafeLoader is failing for a certain edge case. The SafeLoader does not fail under the same circumstances, and neither do the yaml parsers we use in other languages.

specifically it is this which it errors on:
`key1: {key2:{key3:value}}`
Where the a space follows `key1:` but not `key2:`. If a space follows both, or no space follows both it works fine.

From the interpreter:
```
>>> import yaml
>>> y1 = "key1:{key2:value}"
>>> y2 = "key1:{key2:{key3:value}}"
>>> y3 = "key1: {key2:{key3:value}}"
>>> y4 = "key1: {key2: {key3: value}}"
>>> yaml.load(y1, Loader=yaml.SafeLoader)
'key1:{key2:value}'
>>> yaml.load(y2, Loader=yaml.SafeLoader)
'key1:{key2:{key3:value}}'
>>> yaml.load(y3, Loader=yaml.SafeLoader)
{'key1': {'key2': {'key3:value': None}}}
>>> yaml.load(y4, Loader=yaml.SafeLoader)
{'key1': {'key2': {'key3': 'value'}}}
>>> yaml.load(y1, Loader=yaml.CSafeLoader)
'key1:{key2:value}'
>>> yaml.load(y2, Loader=yaml.CSafeLoader)
'key1:{key2:{key3:value}}'
>>> yaml.load(y3, Loader=yaml.CSafeLoader)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dbandfield/.local/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/dbandfield/.local/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:10484)
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:10831)
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:11813)
  File "ext/_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:13717)
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:11813)
  File "ext/_yaml.pyx", line 887, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:13685)
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:13923)
yaml.scanner.ScannerError: while scanning a plain scalar
  in "<unicode string>", line 1, column 8
found unexpected ':'
  in "<unicode string>", line 1, column 12
>>> yaml.load(y4, Loader=yaml.CSafeLoader)
{'key1': {'key2': {'key3': 'value'}}}
```

To be honest I'm not entirely sure which of these cases count as valid YAML (I tried reading the spec and got lost), but the inconsistency between implementations is causing us issues.

**Comment by perlpunk** [comment]
Case 1 and 2 are just strings, no mappings involved. They are valid.
Case 4 is valid and accepted by most parsers.

Case 3 `key1: {key2:{key3:value}}` is detected as invalid by yaml-cpp, libyaml, yaml.js, HsYAML, YamlDotNet and ruamel.yaml.
HsYAML is built on the YAML reference parser.
PyYAML is too permissive here. It should return an error. A space after `key2:` is required.
