### ISSUE TITLE
Bug in pyyaml found by fuzzing

### ISSUE THREAD

**Issue by ingydotnet** [yaml/pyyaml#473]
```
Happy new year Ingy,

Here is a bug found by fuzzing pyyaml

Reproducer is :

import yaml
yaml.load("._:")

Stack trace is :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 72, =
in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 3=
7, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 4=
6, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 3=
98, in construct_yaml_map
    value =3D self.construct_mapping(node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 2=
04, in construct_mapping
    return super().construct_mapping(node, deep=3Ddeep)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 1=
25, in construct_mapping
    key =3D self.construct_object(key_node, deep=3Ddeep)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 8=
6, in construct_object
    data =3D constructor(self, node)
  File "/usr/local/lib/python3.7/site-packages/yaml/constructor.py", line 2=
78, in construct_yaml_float
    return sign*float(value)
ValueError: could not convert string to float: =E2=80=98.'

Cheers,
Philippe
```

**Comment by ingydotnet** [comment]
Reporting a bug that was emailed to me personally.

Simpler case is: `yaml.load("._")`

This does not seem to match the regexp in https://yaml.org/type/float.html

**Comment by perlpunk** [comment]
Duplicate of #168

**Comment by perlpunk** [comment]
Handled by #497
