### ISSUE TITLE
yaml.safe_load(b'._______________________________'): "ValueError: could not convert string to float: '.'"

### ISSUE THREAD

**Issue by wellsonah2019** [yaml/pyyaml#603]
I have found a ValueError crash while running the safe_load and load function with the input b"._________________" on PyYAML version 5.3.1. 

Traceback is as follows: 

```
Traceback (most recent call last):
  File "D:\reproduce-pyyaml.py", line 4, in <module>
    yaml.load(b'._______________________________')
  File "C:\Python310\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Python310\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "C:\Python310\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "C:\Python310\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Python310\lib\site-packages\yaml\constructor.py", line 292, in construct_yaml_float
    return sign*float(value)
ValueError: could not convert string to float: '.'
```

Reproducing the crash:

```
import yaml
yaml.load(b'._______________________________')
```

I understand that there is a version 6.0 of PyYAML now and it does not raise an exception any longer with the same input. However, the [official documentation](https://pyyaml.org/wiki/PyYAML) mentions that 5.3 is still the current stable release therefore I thought this could be a concern to you.

**Comment by perlpunk** [comment]
Yeah, the docs are just out of date. I pinged @ingydotnet who did the releases to update them
