### ISSUE TITLE
PyYAML can't determine constructor for subclass of YAMLObject when CLoader is used

### ISSUE THREAD

**Issue by FynnFreyer** [yaml/pyyaml#621]
Python Version used is 3.10 and PyYAML Version is 6.0

Consider the following two pieces of code:

# Snippet #1
```python3
import yaml


class Foo(yaml.YAMLObject):
    yaml_tag = '!Foo'


if __name__ == '__main__':
    foo = Foo()
    foo_yaml = yaml.dump(foo)
    foo_loaded = yaml.load(foo_yaml, Loader=yaml.Loader)
```

# Snippet #2
```python3
import yaml


class Foo(yaml.YAMLObject):
    yaml_tag = '!Foo'


if __name__ == '__main__':
    foo = Foo()
    foo_yaml = yaml.dump(foo)
    foo_loaded = yaml.load(foo_yaml, Loader=yaml.CLoader)
```

These are identical, except for the used Loader.

Snippet #1 works, while Snippet #2 raises with the following traceback:

```
Traceback (most recent call last):
  File "/path/to/project/src/test.py", line 13, in <module>
    foo_loaded = load(foo_yaml, Loader=CLoader)  # should work I think, but raises
  File "/path/to/project/venv/lib64/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/path/to/project/venv/lib64/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/path/to/project/venv/lib64/python3.10/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/path/to/project/venv/lib64/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/path/to/project/venv/lib64/python3.10/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!Foo'
  in "<unicode string>", line 1, column 1

Process finished with exit code 1
```

This seems to me to be a problem

**Comment by perlpunk** [comment]
Try:
```
class Foo(yaml.YAMLObject):
    yaml_tag = '!Foo'
    yaml_loader = yaml.CLoader
```

**Comment by FynnFreyer** [comment]
Works perfectly! Thanks for helping me out!
