### ISSUE TITLE
Fail to parse Yaml text if there is a value starts with "%"

### ISSUE THREAD

**Issue by xinzhang-lotusflare** [yaml/pyyaml#644]
Hi team,

when using pyyaml to analyze yaml files, we noticed an issue that if there is a value starts with `%`, it will throw exception directly.

Example:

```
from yaml import load
try:
    from yaml import CLoader as Loader, CDumper as Dumper
except ImportError:
    from yaml import Loader, Dumper

valid_test_yaml = """
name: x%{aaa}
"""

invalid_test_yaml = """
name: %{aaa}
"""


if __name__ == '__main__':
    data = load(valid_test_yaml, Loader=Loader) # succeeded
    print(data)
    data = load(invalid_test_yaml, Loader=Loader) # failed
    print(data)
```

Output:

```
{'name': 'x%{aaa}'}
Traceback (most recent call last):
  File "/Users/zhangxin/PycharmProjects/pyyaml-demo/main.py", line 19, in <module>
    data = load(invalid_test_yaml, Loader=Loader) # failed
  File "/Users/zhangxin/PycharmProjects/pyyaml-demo/venv/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/zhangxin/PycharmProjects/pyyaml-demo/venv/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 694, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning for the next token
found character that cannot start any token
  in "<unicode string>", line 2, column 7

Process finished with exit code 1
```

I think either case doesn't violate the YAML specification.

## Context

System: MacOS 12.4
Python Version:  3.9.12
PyYAML Version: 6.0

**Comment by perlpunk** [comment]
It is invalid to have a percent sign as the first character of the plain string.
See https://yaml.org/spec/1.2.2/#rule-ns-plain-first and https://yaml.org/spec/1.2.2/#rule-c-indicator

**Comment by xinzhang-lotusflare** [comment]
Thanks, my bad. I should have taken closer look at the spec.
