### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by alphaniner** [yaml/pyyaml#657]
According to the documentation (both [pyaml.org](https://pyyaml.org/wiki/PyYAMLDocumentation) as well as `help(yaml)`) the default value of `default_flow_style` is `None`. But I get different output if I explicitly specify it:
```
>>> mydict = {'key': {'a_string': 'a string', 'a_list': ['a', 'b']}}
>>> print(yaml.dump(mydict))
key:
  a_list:
  - a
  - b
  a_string: a string

>>> print(yaml.dump(mydict, default_flow_style=None))
key:
  a_list: [a, b]
  a_string: a string
```
Unless I'm misunderstanding something, it seems the documentation was never updated to reflect #199/https://github.com/yaml/pyyaml/commit/f20936573840842954b933801abeeaedad977b41.

**Comment by denizdogan** [comment]
Agreed, the documentation looks very old. I'm not sure if anyone in the team saw this? So I'm bumping it, I guess.

**Comment by lurch** [comment]
See also #687

**Comment by scajanus** [comment]
+1 For this -- the linked documentation is also using Python 2 syntax for printing, e.g.

```
import yaml
document = """
  a: 1
  b:
    c: 3
    d: 4
"""
print yaml.dump(yaml.load(document))
```
with a print statement instead of function.

**Comment by ferdnyc** [comment]
In addition to the issues already mentioned, the documentation also says, at several points, things like,

> {`load(stream)`, `safe_load(stream)`} parses the given stream and returns a Python object constructed from for the first document in the stream.

...But that's not entirely correct. What it'll actually do is parse the given stream, return a Python object for the contents if there's exactly one document, and raise an exception if it finds anything more than that:

```python
>>> with open("something_with_frontmatter.md") as f:
...     data = yaml.safe_load(f.read())
...
Traceback (most recent call last):
  File "<python-input-10>", line 2, in <module>
    data = yaml.safe_load(f.read())
  File "/usr/lib64/python3.13/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib64/python3.13/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python3.13/site-packages/yaml/composer.py", line 41, in get_single_node
    raise ComposerError("expected a single document in the stream",
            document.start_mark, "but found another document",
            event.start_mark)
yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 2, column 1:
    flags:
    ^
but found another document
  in "<unicode string>", line 10, column 1:
    ---
    ^
```
