### ISSUE TITLE
How to validate "{{- toYaml }}"  inside YAML?

### ISSUE THREAD

**Issue by melezhik** [yaml/pyyaml#676]
Hi devs!

I have following yaml:

```yaml
{{- toYaml .Values | nindent 8 }}
foo: bar 
```

And have an error when parse this string using pyyaml:

```python
from yaml import load

try:
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader

yaml = """
{{- toYaml .Values | nindent 8 }}
foo: bar
"""

print(yaml)

load(yaml,Loader=Loader)
```

```
{{- toYaml .Values | nindent 8 }}
foo: bar

Traceback (most recent call last):
  File "/tmp/foo6.py", line 18, in <module>
    load(yaml,Loader=Loader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 889, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 887, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a flow node
did not find expected node content
  in "<unicode string>", line 2, column 3
```

How can I make "load" successfully parse this yaml, I am looking for a way to initialize `.Values` in load call, something link this:

```python
load(yaml,Loader=Loader, context={ "Values": { "bar":  "bar" }   });
```

If something like this is possible?

**Comment by melezhik** [comment]
thanks
