### ISSUE TITLE
First time to run. Not working.

### ISSUE THREAD

**Issue by MrUnknown789556** [yaml/pyyaml#708]
I just installed the PyYAML package by pip. And the other few modules mentioned in top of script.
I get several errors when trying to run.

What is the problem? Something with my installation, my environment etc.?
I use Windows 11. python 3.10. pip 23.0.1.

C:\Users\fn31\Desktop\pe>Python entry.py Micro.pdf -o Micro.yaml
Traceback (most recent call last):
  File "C:\Users\fn31\Desktop\pe\entry.py", line 236, in <module>
    run()
  File "C:\Users\fn31\Desktop\pe\entry.py", line 232, in run
    main(args.in_files, args.out_file)
  File "C:\Users\fn31\Desktop\pe\entry.py", line 179, in main
    pl = get_pagelabels(doc)
  File "C:\Users\fn31\Desktop\pe\entry.py", line 72, in get_pagelabels
    if Name.PageLabels not in doc.root:
AttributeError: 'pikepdf._core.Pdf' object has no attribute 'root'. Did you mean: 'Root'?

C:\Users\fn31\Desktop\pe>

**Comment by nitzmahone** [comment]
PyYAML isn't even in the callstack here- guessing your problem lies elsewhere.
