### ISSUE TITLE
Style `|` in combination with `\n` in the beginning renders invalid yaml

### ISSUE THREAD

**Issue by aquamatthias** [yaml/pyyaml#717]
`yaml.dumps` with default_style `|` and a string that starts with `\n` renders invalid yaml:

Example:
```python
yaml.dump("\none\ntwo\nthree", default_style="|")
|2-

  one
  two
  three
```

So it renders a `2` after the pipe symbol. The expected result would look like this:

```yaml
|-

  one
  two
  three
```

It renders correctly for strings that do not start with a line break:
```
yaml.dump("one\ntwo\nthree", default_style="|")
|-
  one
  two
  three
  ```

After playing with the parameters I realized the number reflects the number of indents.

```
yaml.dump("\none\ntwo\nthree", indent=6, default_style="|")
|6-

      one
      two
      three
```

The generated yaml can also not be read by pyyaml back again:
```python
    def parse_block_mapping_key(self):
        if self.check_token(KeyToken):
            token = self.get_token()
            if not self.check_token(KeyToken, ValueToken, BlockEndToken):
                self.states.append(self.parse_block_mapping_value)
                return self.parse_block_node_or_indentless_sequence()
            else:
                self.state = self.parse_block_mapping_value
                return self.process_empty_scalar(token.end_mark)
        if not self.check_token(BlockEndToken):
            token = self.peek_token()
>           raise ParserError("while parsing a block mapping", self.marks[-1],
                    "expected <block end>, but found %r" % token.id, token.start_mark)
E           yaml.parser.ParserError: while parsing a block mapping
E             in "<unicode string>", line 3, column 5:
E                   ~/.aws/credentials: |6
E                   ^
E           expected <block end>, but found '['
E             in "<unicode string>", line 5, column 7:
E                     [default]
E                     ^

../../venv/lib/python3.11/site-packages/yaml/parser.py:438: ParserError

```

**Comment by perlpunk** [comment]
Can you please create a small reproducer and tell us which pyyaml version you have?
I can't reproduce the error. The digit after the `|` is indeed the number of indentation spaces, see [here](https://www.yaml.info/learn/quote.html#indent), and it's valid YAML.


```
>>> import yaml
>>> yaml.__version__
'6.0'
>>> out = yaml.dump("\none\ntwo\nthree", indent=6, default_style="|")
>>> print(out)
|6-

      one
      two
      three

>>> yaml.safe_load(out)
'\none\ntwo\nthree'
>>> 
>>> out = yaml.dump("\none\ntwo\nthree", default_style="|")
>>> print(out)
|2-

  one
  two
  three

>>> yaml.safe_load(out)
'\none\ntwo\nthree'

```

**Comment by aquamatthias** [comment]
Here is the reproducer script:

```python
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.__version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'yaml' has no attribute '__version'. Did you mean: '__version__'?
>>> 
>>> doc = """
... resotoworker:
...   files_in_home_dir:
...     ~/.aws/credentials: |6
... 
...       [default]
...       aws_access_key_id=xxxx
...       aws_secret_access_key=yyyy
...       cli_pager=
... """
>>> 
>>> # will fail
>>> yaml.safe_load(doc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/Users/matthias/Library/Python/3.11/lib/python/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 4, column 5:
        ~/.aws/credentials: |6
        ^
expected <block end>, but found '['
  in "<unicode string>", line 6, column 7:
          [default]
          ^
>>> 
>>> # will succeed
>>> yaml.safe_load(doc.replace("6", ""))
{'resotoworker': {'files_in_home_dir': {'~/.aws/credentials': '\n[default]\naws_access_key_id=xxxx\naws_secret_access_key=yyyy\ncli_pager=\n'}}}
```

The yaml with the number is not valid according to yamllint - so I guess it is fine blowing up..

Let me show you how this yaml snippet has been created.
I can not use pyyaml to create the yaml for the whole document, since I need to add comments in the resulting file.
So I render the document myself, while the values are rendered via pyyaml.

```python
def safe_string(s: str, indent: int, default_style: Optional[str] = None) -> str:
      # 2 spaces per indent
      yaml.dump(s, indent=indent * 2, allow_unicode=True, width=sys.maxsize, default_style=default_style)
```

So the 6 comes from the code that dumped a string with style="|" 3 levels deep.

**Comment by perlpunk** [comment]
Your example document is invalid, right.
But this wasn't created by pyyaml, like you said yourself.
The number after the `|` is valid, believe me.

The problem with your document is that the string isn't indented enough.

It's not a pyyaml bug, and you need to fix the script that is creating the invalid YAML.

**Comment by perlpunk** [comment]
This is how your doc should look like to be valid:
```
resotoworker:
  files_in_home_dir:
    ~/.aws/credentials: |6

          [default]
          aws_access_key_id=xxxx
          aws_secret_access_key=yyyy
          cli_pager=
```
Load this with pyyaml and you'll see it will be loaded without an error.
Also yamllint accepts this.

**Comment by aquamatthias** [comment]
Thanks @perlpunk 
So is there an option in pyyaml to render a value while defining the indentation?
I was under the impression this is what `indent` is good for - but it seems I interpreted it in the wrong way..

**Comment by aquamatthias** [comment]
Ok. I will do the indentation on the script side. Some better documentation would have helped me a lot. 
Thanks for looking into it.

**Comment by perlpunk** [comment]
The `indent` option is for specifying how many spaces to use for indentation per level, or in a block scalar
e,g. 2
```
a:
  b:
    c: d
```
vs. 4
```
a:
    b:
        c: d
```

I don't know how you create your string, but I assume you do the following: you dump a string in block style and get
```
|6-

      one
      two
      three
```
and then you take that dump and append it manually behind a mapping key:
```
foo: |6-

      one
      two
      three
```
As a result, the indentation is too low, because a value in a mapping needs to be indented more (at least 1 space), because the 6 tells pyyaml that the content of the block scalar is indented with 6 spaces. So you need to do the necessary indentation yourself.

The digit after the block scalar indicator is explained in the link I gave you earlier.
There is no other option in pyyaml to tell it "hey, this will be inserted into an existing document in a position with with indentation x".
The good thing is, you can easily do that yourself. Just prepending the amount of spaces to every line should be enough (except the first line with the `|` of course).
