### ISSUE TITLE
ConstructorError: could not determine a constructor for the tag '!reference'

### ISSUE THREAD

**Issue by AlexanderSerov** [yaml/pyyaml#825]
We are using !reference [feature](https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#reference-tags) of gitlab and it perfectly parsed by CI. But yml parsing by PyYaml is failed.

Minimal reproduce example:
test.py:
```python
import yaml
from yaml.loader import SafeLoader

with open('test.yml') as f:
        data = yaml.load(f, Loader=SafeLoader)
```
test.yml:
```yml
script:
  - !reference ['some_reference']
```
Run and fail log:
```
[root@df3a2ce3fdf5 install]# python3 test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    data = yaml.load(f, Loader=SafeLoader)
  File "/usr/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 130, in construct_sequence
    for child in node.value]
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 130, in <listcomp>
    for child in node.value]
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 429, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!reference'
  in "test.yml", line 2, column 5
```

**Comment by perlpunk** [comment]
`!reference` is not a standard YAML tag. It's a custom tag used by Gitlab.
Depending on what you want to get as a result, you need to add a custom constructor.
Here is one that simply returns the sequence:
```
class gitlabLoader(SafeLoader):
    pass

def construct_reference(l, node):
    data = l.construct_sequence(node)
    return data

yaml.add_constructor('!reference', construct_reference, gitlabLoader);
with open('test.yml') as f:
data = yaml.load(f, Loader=gitlabLoader)
```

**Comment by AlexanderSerov** [comment]
Thanks! I reuse following implementation
https://github.com/DataDog/datadog-agent/blob/c480864cb17f78fbaa5adce4ba031fbe6f95f8c9/tasks/pipeline.py#L55

**Comment by perlpunk** [comment]
I don't recommend to modify the SafeLoader directly. It will change it globally.
This influences every other part of a program that is loading YAML and is using the SafeLoader.
It's a good practice to use your own class and inherit from SafeLoader or one of the other pyyaml classes.
