### ISSUE TITLE
pyymal 5.4.1 will not install whatsoever, been here on same step for days.

### ISSUE THREAD

**Issue by paymepaI** [yaml/pyyaml#838]
hello, my first post lol , so im kinda newish to terminal, only use it for sql injections , but i am trying to install the spiderfoot osint tool , i encounter an issue of pyyaml not installing whatsoever, ive tried ai, reddit, my space, everything ...
i need pyymal 5.4.1 specifically to install spiderfoot and other various products. 

this is the spiderfoot commands i am reffering to 

 wget https://github.com/smicallef/spiderfoot/archive/v4.0.tar.gz
 tar zxvf v4.0.tar.gz
 cd spiderfoot-4.0
 pip3 install -r requirements.txt
 python3 ./sf.py -l 127.0.0.1:5001

the following is what i encounter for when i plug my commands in . ( step 4 i get the pyyaml5.4.1 issue )

pip3 install pyyaml==5.4.1
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ghauri-1.3.8-py3.13.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting pyyaml==5.4.1
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 271, in <module>
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 994, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 312, in run
          self.find_sources()
          ~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
          mm.run()
          ~~~~~~^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 543, in run
          self.add_defaults()
          ~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 581, in add_defaults
          sdist.add_defaults(self)
          ~~~~~~~~~~~~~~~~~~^^^^^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/command/sdist.py", line 109, in add_defaults
          super().add_defaults()
          ~~~~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
          ~~~~~~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/4j/xnl81bd15xd_dn54c_lc3k4r0000gn/T/pip-build-env-53qo2mc0/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

i actually wanna cry out of frustration, plus im new to terminal, so i wanna go jump off a bridge now, pls help :(

**Comment by irodotos7** [comment]
I was having a similar problem when I was using python3.12 and when I changed the version to python3.9.7 it worked

**Comment by yoelcabo** [comment]
Check this: https://github.com/yaml/pyyaml/issues/724
