### ISSUE TITLE
yaml.load() does not assert input type

### ISSUE THREAD

**Issue by kupsef** [yaml/pyyaml#91]
```
from mock import MagicMock
import yaml

# this will consume all available memory
yaml.load(MagicMock())
```
This situation may look forced, but this can easily happen by mistake while testing, and it is not evident what causes the hang in the first place.

In contrast, if you try this with the json library, it will fail:
```
>>> json.load(MagicMock())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by CiFFiRO** [comment]
Hello.
I can add that it also uses a lot of memory. I spent a decent amount of time debagging this case (MagicMock in json.load). Absolutely unexpected behavior from json.load . Please add any check argument type in json.load function.
