### ISSUE TITLE
Unicode anchor and alias names are not supported.

### ISSUE THREAD

**Issue by peterkmurphy** [yaml/pyyaml#94]
The YAML standard allows (almost) any printable character as part of an anchor name. There are exceptions, such as white space, the BOM, and “[”, “]”, “{”, “}” and “,” characters. Never the less, the following code should be valid YAML:

    # Songwriters: (gb) West Richard / Colin Gilbert Angus / Richard (gb) West
    # Ebeneezer Goode lyrics © Warner/Chappell Music, Inc
    - &😁 "'Eezer Goode 'Eezer Goode He's Ebeneezer Goode"
    - *😁

I get the following errors:

```
Traceback (most recent call last):
  File "/home/peter/other-projects/wordschool/testemoticons.py", line 3, in <module>
    for report in reportdata:
  File "/home/peter/other-projects/wordschool/local/lib/python2.7/site-packages/yaml/__init__.py", line 80, in load_all
    loader = Loader(stream)
  File "/home/peter/other-projects/wordschool/local/lib/python2.7/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/home/peter/other-projects/wordschool/local/lib/python2.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/peter/other-projects/wordschool/local/lib/python2.7/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/home/peter/other-projects/wordschool/local/lib/python2.7/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/home/peter/other-projects/wordschool/local/lib/python2.7/site-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x1f601: special characters are not allowed
  in "ebeneezergoode.yml", position 132

```
Note that the code for indicating the location of the errant character is not working.

**Comment by eschnett** [comment]
In addition to unicode characters, many interesting special characters such as `/` or `.` are also not allowed in anchor names.

There is a respective comment in the Python source code that states that YAML does not restrict characters in anchors (it actually does in YAML 1.2 -- the five characters `,[]{}` are not allowed), and thus decides to disallow all non-alphanumeric characters.

I really would like to have hierarchical anchor names.
